export const ADD_BLOCK_START = "ADD_BLOCK_START";
export const ADD_BLOCK_SUCCESS = "ADD_BLOCK_SUCCESS";
export const MODIFY_BLOCK = "MODIFY_BLOCK";
export const REVALIDATE_BLOCK_START = "REVALIDATE_BLOCK_START";
export const REVALIDATE_BLOCK_SUCCESS = "REVALIDATE_BLOCK_SUCCESS";
export const CHANGE_DIFFICULTY = "CHANGE_DIFFICULTY";
